title: 
  | Núcleo Académico
  | Maestría en Ciencia de Datos
  | Universidad de Sonora 
description: Universidad de Sonora
logo: https://mcd.unison.mx/wp-content/themes/awaken/img/logo_mcd.png
theme: jekyll-theme-minimal
